# Generated by Django 2.1.3 on 2019-03-04 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('dislikesongs', models.ManyToManyField(related_name='forbiddenplaylists', to='music.Song')),
                ('relatedplaylists', models.ManyToManyField(related_name='_playlist_relatedplaylists_+', to='music.Playlist')),
                ('songs', models.ManyToManyField(related_name='playlists', through='music.Listing', to='music.Song')),
            ],
        ),
        migrations.AddField(
            model_name='listing',
            name='playlist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.Playlist'),
        ),
        migrations.AddField(
            model_name='listing',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.Song'),
        ),
    ]
