# Generated by Django 2.1.3 on 2019-03-13 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='filetype',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
