# Generated by Django 2.1.3 on 2019-03-19 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_song_filetype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='arranger',
        ),
        migrations.RemoveField(
            model_name='song',
            name='author',
        ),
        migrations.RemoveField(
            model_name='song',
            name='conductor',
        ),
        migrations.RemoveField(
            model_name='song',
            name='discsubtitle',
        ),
        migrations.RemoveField(
            model_name='song',
            name='isrc',
        ),
        migrations.RemoveField(
            model_name='song',
            name='language',
        ),
        migrations.RemoveField(
            model_name='song',
            name='lyricist',
        ),
        migrations.RemoveField(
            model_name='song',
            name='media',
        ),
        migrations.RemoveField(
            model_name='song',
            name='mood',
        ),
        migrations.RemoveField(
            model_name='song',
            name='musicbrainz_albumartistid',
        ),
        migrations.RemoveField(
            model_name='song',
            name='musicbrainz_albumid',
        ),
        migrations.RemoveField(
            model_name='song',
            name='musicbrainz_albumstatus',
        ),
        migrations.RemoveField(
            model_name='song',
            name='musicbrainz_albumtype',
        ),
        migrations.RemoveField(
            model_name='song',
            name='musicbrainz_artistid',
        ),
        migrations.RemoveField(
            model_name='song',
            name='musicbrainz_trackid',
        ),
        migrations.RemoveField(
            model_name='song',
            name='musicbrainz_trmid',
        ),
        migrations.RemoveField(
            model_name='song',
            name='musicip_fingerprint',
        ),
        migrations.RemoveField(
            model_name='song',
            name='musicip_puid',
        ),
        migrations.RemoveField(
            model_name='song',
            name='replaygain',
        ),
        migrations.RemoveField(
            model_name='song',
            name='replaygainpeak',
        ),
        migrations.RemoveField(
            model_name='song',
            name='version',
        ),
        migrations.RemoveField(
            model_name='song',
            name='website',
        ),
    ]
