# Generated by Django 2.1.3 on 2019-03-06 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_auto_20190304_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='kind',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
