# Generated by Django 2.1.3 on 2019-03-24 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_auto_20190324_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='rating',
            field=models.IntegerField(null=True),
        ),
    ]
